version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: redash_redis

  redash:
    image: redash/redash:latest
    container_name: redash_server
    depends_on:
      - db
      - redis
    environment:
      REDASH_DATABASE_URL: postgresql://postgres:postgres@db:5432/redash
      REDASH_REDIS_URL: redis://redis:6379/0
    volumes:
      - redash_data:/app/data
    entrypoint: []
    command: ["bash", "-c", "if [ ! -f /app/data/.redash_initialized ]; then /app/bin/docker-entrypoint create_db && touch /app/data/.redash_initialized || true; fi; exec /app/bin/docker-entrypoint server"]
    ports:
      - "5000:5000"

  redash_worker:
    image: redash/redash:latest
    container_name: redash_worker
    depends_on:
      - redash
    environment:
      REDASH_DATABASE_URL: postgresql://postgres:postgres@db:5432/redash
      REDASH_REDIS_URL: redis://redis:6379/0
    command: worker

  generator:
    build: ./generator
    depends_on:
      - db
    restart: always

volumes:
  pgdata:
  redash_data:
